### ISSUE TITLE
[bug] - sign in does not work - [8948db3]

### ISSUE THREAD

**Issue by kimchirice** [codesydney/woc#68]
## scenario
![Screen Shot 2021-08-08 at 11 12 10](https://user-images.githubusercontent.com/36904351/128620388-c594f04d-7c2c-4d7d-a984-48d36c807347.png)

### 1. making sure the server and web both started successfully,

  

- server

  ```node
    ➜  server git:(dev) ✗ nodemon
    [nodemon] 2.0.7
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching path(s): *.*
    [nodemon] watching extensions: js,mjs,json
    [nodemon] starting `node server.js`

    ```

 

- start web

  ```node
    Compiled successfully!
    
    You can now view woc-web in the browser.
    
      Local:            http://localhost:3000
      On Your Network:  http://10.0.10.103:3000
    
    Note that the development build is not optimized.
    To create a production build, use npm run build.
    
  ```

### 2. trying to sing in with account 

    ```json
    {
        "email": "tam.north@hmail.com",
        "password": "S5yYpBaxue2F7RJ!@#"
    }
    ```

### 3. at the server

  ```node
  ➜  server git:(dev) ✗ nodemon
  [nodemon] 2.0.7
  [nodemon] to restart at any time, enter `rs`
  [nodemon] watching path(s): *.*
  [nodemon] watching extensions: js,mjs,json
  [nodemon] starting `node server.js`
  [2021-08-08T02:04:48.440Z] [INFO] [SERVER] Server running on localhost:8080
  [2021-08-08T02:04:48.836Z] [INFO] [SERVER] Mongo connected
  [2021-08-08T02:06:08.859Z] [INFO] [SERVER-UTIL] Method - [POST], URL - [/api/auth/login], IP - [::ffff:127.0.0.1]
  (node:5497) UnhandledPromiseRejectionWarning: Error: "expiresIn" should be a number of seconds or string representing a timespan
      at /Users/carmel/code/kimchirice/code.base/code_sydney_woc/server/node_modules/jsonwebtoken/sign.js:52:15
      at Array.forEach (<anonymous>)
      at validate (/Users/carmel/code/kimchirice/code.base/code_sydney_woc/server/node_modules/jsonwebtoken/sign.js:43:6)
      at validateOptions (/Users/carmel/code/kimchirice/code.base/code_sydney_woc/server/node_modules/jsonwebtoken/sign.js:58:10)
      at Object.module.exports [as sign] (/Users/carmel/code/kimchirice/code.base/code_sydney_woc/server/node_modules/jsonwebtoken/sign.js:141:5)
      at Object.signToken (/Users/carmel/code/kimchirice/code.base/code_sydney_woc/server/utils/auth.util.js:33:23)
      at module.exports.login (/Users/carmel/code/kimchirice/code.base/code_sydney_woc/server/controller/auth.controller.js:48:37)
  (Use `node --trace-warnings ...` to show where the warning was created)
  (node:5497) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
  (node:5497) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  ```

## version:  **8948db3**

  ```node
  code_sydney_woc git:(dev) ✗ git log --oneline          
  8948db3 (HEAD -> dev, origin/dev) Merge pull request #64 from codesydney/02_FooterComponent
  0cba9f2 (origin/02_FooterComponent) Footer styles created
  8948db3 (HEAD -> dev, origin/dev) Merge pull request #64 from codesydney/02_FooterComponent
  0cba9f2 (origin/02_FooterComponent) Footer styles created
  40b761d fixed errors
  6ee97a4 package-lock.json
  940b790 npm
  0511c39 Color of paragraph changed
  fe2f2e5 First version of the Footer
  e1dec00 Merge branch 'dev' of https://github.com/codesydney/woc into dev ok
  af69032 Merge branch '03_05_UserEvents' of https://github.com/codesydney/woc into 03_05_UserEvents
  945719f Fixing error
  aadbac8 (review_pr_57, error_msg_position) Merge pull request #56 from codesydney/ep01_api_validate
  ```

**Comment by kimchirice** [comment]
## update

1.  quick read error msg
  ```
  at module.exports.login(/Users/carmel/code/kimchirice/code.base/code_sydney_woc/server/controller/auth.controller.js:48:37)
  ```
2. then check ```server/controller/auth.controller.js``` line ***48***

![Screen Shot 2021-08-08 at 17 04 24](https://user-images.githubusercontent.com/36904351/128623967-b849ae97-b464-43c4-9040-cd6b3613beff.png)

3. go to file ```server/utils/auth.utils.js```
```
/**
 * a function takes in dataObj,  
 * 
 * @param {object} dataObj payload object
 * @returns valid jwt token
 */
const signToken = async (dataObj) => {
    const expires = process.env.JWT_EXP;
    console.log(`current expires is ${expires}`)
    const SECRET = process.env.JWT_SECRET;

    const payload = {
        ...dataObj,
    };

    const token = jwt.sign(payload, SECRET, { expiresIn: expires });
    return {
        token,
        expiresIn: expires,
    };
};
```

4. check ```server/.env```, and there was no variable declared of JWT_EXP. add a new one, then check

- now the server side

```node
➜  server git:(debug_signIn) ✗ nodemon
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
[2021-08-08T07:00:12.951Z] [INFO] [SERVER] Server running on localhost:8080
[2021-08-08T07:00:13.393Z] [INFO] [SERVER] Mongo connected
[2021-08-08T07:00:32.025Z] [INFO] [SERVER-UTIL] Method - [POST], URL - [/api/auth/login], IP - [::ffff:127.0.0.1]
current expires is 600
[2021-08-08T07:00:36.176Z] [INFO] [SERVER-UTIL] Method - [POST], URL - [/login], IP - [::ffff:127.0.0.1], STATUS - [null]
[2021-08-08T07:00:36.643Z] [INFO] [SERVER-UTIL] Method - [GET], URL - [/api/user], IP - [::ffff:127.0.0.1]
[2021-08-08T07:00:36.651Z] [INFO] [SERVER-UTIL] Method - [GET], URL - [/user], IP - [::ffff:127.0.0.1], STATUS - [null]
[2021-08-08T07:00:36.705Z] [INFO] [SERVER-UTIL] Method - [GET], URL - [/api/user], IP - [::ffff:127.0.0.1]
[2021-08-08T07:00:36.708Z] [INFO] [SERVER-UTIL] Method - [GET], URL - [/user], IP - [::ffff:127.0.0.1], STATUS - [null]
[2021-08-08T07:00:36.724Z] [INFO] [SERVER-UTIL] Method - [GET], URL - [/api/user], IP - [::ffff:127.0.0.1]
[2021-08-08T07:00:36.726Z] [INFO] [SERVER-UTIL] Method - [GET], URL - [/user], IP - [::ffff:127.0.0.1], STATUS - [null]
[2021-08-08T07:00:36.743Z] [INFO] [SERVER-UTIL] Method - [GET], URL - [/api/user], IP - [::ffff:127.0.0.1]
[2021-08-08T07:00:36.758Z] [INFO] [SERVER-UTIL] Method - [GET], URL - [/user], IP - [::ffff:127.0.0.1], STATUS - [null]
```

- from browser devtool, we could see the response

```json
{
    "namespace":"VERIFYTOKEN",
    "msg":"failed authentication"
}
```
![Screen Shot 2021-08-08 at 17 12 23](https://user-images.githubusercontent.com/36904351/128624129-da832c36-6a85-4358-b63a-b2f30da0bba2.png)

**Comment by kimchirice** [comment]
closed the issue as adding related the .env setting fix the problem
